export enum mapEventEnum {
  change = 'change',
  change_layerGroup = 'change:layerGroup',
  change_size = 'change:size',
  change_target = 'change:target',
  change_view = 'change:view',
  click = 'click',
  dblclick = 'dblclick',
  error = 'error',
  loadend = 'loadend',
  loadstart = 'loadstart',
  moveend = 'moveend',
  movestart = 'movestart',
  pointerdrag = 'pointerdrag',
  pointermove = 'pointermove',
  postcompose = 'postcompose',
  postrender = 'postrender',
  precompose = 'precompose',
  propertychange = 'propertychange',
  rendercomplete = 'rendercomplete',
  singleclick = 'singleclick',
}
